services:
  db:
    build:
      context: .
      dockerfile: ./infra/db/Dockerfile
    environment:
      MYSQL_DATABASE: app_test
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3306:3306"
    volumes:
      - rails-railway-stations-volume:/var/lib/mysql
  web:
    build:
      context: .
      dockerfile: ./infra/web/Dockerfile
    # command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    command: bash -c "rm -f tmp/pids/server.pid && rdbg -n --open --host 0.0.0.0 --port 12345 -c -- bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
      - rails-railway-stations-volume:/var/lib/mysql
    ports:
      - "3000:3000"
      - "12345:12345"
    links:
      - db

volumes:
  rails-railway-stations-volume:
  bundle:
